FROM postgres:latest

ENV POSTGRES_DB=${DB_NAME}
ENV POSTGRES_USER=${DB_USER}
ENV POSTGRES_PASSWORD=${DB_PASSWORD}

COPY script_bdd/CreateTable.sql /docker-entrypoint-initdb.d/
COPY script_bdd/InsertData.sql /docker-entrypoint-initdb.d/
